### ISSUE TITLE
404 Error 1.9 Magento

### ISSUE THREAD

**Issue by odetas** [arkadedigital/magento-s3#11]
Hi- I've copied the app/ directory over to the root directory for Magento via app/

When I head over to System-Configuration-Arkade Extensions-S3, I get a 404 error.  On System-Configuration-Advanced S3 is a storage option for Storage Configuration for Media.  Is there any pointers on how I should go about fixing this error? Permissions perhaps?

**Comment by thomas-seres** [comment]
Hi ! 
I think you just have to logout from the admin, login again and all should be good.

It's a common issue when you add a new module in magento.
Waiting for your feedback to help more if your issue is not resolved,

Cheers !

**Comment by odetas** [comment]
Thomas- I'm feeling really dumb right now.  I must've tried so many things, except this one basic tenet.  Thank you very much, and I hope someone else will crawl onto this as well.
