### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by rafafortes** [arkadedigital/magento-s3#14]
Magento is using old url's for media after follow all steps of installation. I've used composer and aplied nginx location conf.

**Comment by rafafortes** [comment]
My workaround was change url media base manually

**Comment by thaiphan** [comment]
Hey @rafafortes,

Yeah, the S3 extension does not provide any functionality to automatically change the media URL to S3. You have to change it manually like you've described.

Is everything else working fine besides this?

Regards,

Thai

**Comment by rafafortes** [comment]
My mistake, sorry dude!

You did a nice job with the module. Everything is working fine, congrats!

Att,

Rafael Fortes

*Skype:* r_fortes
*Google Talk*: rafael.pfortes@gmail.com
*Linkedin:* http://br.linkedin.com/pub/rafael-dos-passos-fortes/23/246/370

2016-08-04 20:37 GMT-03:00 Thai Phan <notifications@github.com>:

**Comment by thaiphan** [comment]
Cool, I'll close this issue then!
