### ISSUE TITLE
Magento 1.9x, clarification

### ISSUE THREAD

**Issue by vivekam101** [arkadedigital/magento-s3#2]
Magento is still storing images in local server instead of S3. I have saved the settings to store media storage to Amazon S3 after the sync. Can you help if i did something wrong ?

**Comment by thaiphan** [comment]
Hey @vivekam101,

Depending on your settings, Magento will download images from S3 back onto the file server. Your images should have been uploaded to S3 but. You can stop Magento from downloading stuff to the file server by changing the media URL to S3 or CloudFront.

Can you check to see if your images are being stored in S3?

Regards,

Thai

**Comment by vivekam101** [comment]
I have changed the settings @ magento>admin>Configuration>system>Storage Configuration for Media to Amazon S3. Is there any other place where i need to do the changes?

**Comment by thaiphan** [comment]
Hey @vivekam101,

Yeah that's fine. Are your images showing up in S3?

Regards,

Thai

**Comment by vivekam101** [comment]
I guess its the problem with Multivendor extension i'm using where it might be coded to save in local server. Let me check. Thanks Thaipan.

**Comment by thaiphan** [comment]
@vivekam101 Okay, tell us how you go!

**Comment by thomas-seres** [comment]
Hi @vivekam101  !
After synchronize to S3 have you save the configuration ?

If you refresh and check the storage configuration media, is S3 is selected ?

**Comment by vivekam101** [comment]
Yes it is ther. I doubl checked. I think the custom extension is not
checking the base_url for media. Thanks a lot for your responses. I will
let you know the results.

On Monday 21 March 2016, Thomas SERES <notifications@github.com> wrote:

> Hi @vivekam101 <https://github.com/vivekam101> !
> After synchronize to S3 have you save the configuration ?
>
> If you refresh and check the storage configuration media, is S3 is
> selected ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/arkadedigital/magento-s3/issues/2#issuecomment-199266605>
>


-- 
-
Thanks & Regards,
        Vivek T V

**Comment by thaiphan** [comment]
Yeah you have to save configuration for the extension to start working!

**Comment by vivekam101** [comment]
i'm trying to revert the settings to local server and when i do i'm getting an extra get.php along the path to media files. How can i get rid of that? can u please help.

Example: http://url/get.php/media/codes/40.png

**Comment by thaiphan** [comment]
What page in particular are you seeing that page?

**Comment by thaiphan** [comment]
Hey @vivekam101,

Do you still need help?

Regards,

Thai
