### ISSUE TITLE
Media links doesn't point to s3 after sync

### ISSUE THREAD

**Issue by pervak** [arkadedigital/magento-s3#24]
Hello!

 We have sync media folder to s3 via

`php s3_export.php --force`

 It has been sync successfully and wrote "Updating configuration to use S3.", this option also  appeared in admin.

 But the links on the front-end remains pointing on site media folder rather then to s3 URL.

 We'd clear var/cache, reindex catalog, but everything stay the same.

 What's wrong and how to force using s3 urls?

**Comment by tejaspatel2014** [comment]
Hi Pervak,

You can not use S3 urls. However you can connect your s3 with cloudFront (any CDN) and add cloudFront url in magento admin > configuration > web > medial urls

Regards
