### ISSUE TITLE
Favicon and logo image uploads being saved with an extra slash in path inside database

### ISSUE THREAD

**Issue by sjafferali** [arkadedigital/magento-s3#4]
Noticed a bug with the way this behaves that is specific to favicon uploads and logo uploads. 

**Steps to reproduce uploading favicon:**
1. Enable extension as per wiki instructions and configure uploads to be uploaded to S3. 
2. Login to the Magento Admin Dashboard
3. Navigate to System >> Configuration >> Design
4. Click on the "HTML Head" section to expand it. 
5. Under the "Favicon Icon" option, click browse and upload a Favicon (any image will work for testing purposes)
6. Click "Save Config" at the top to upload the image and save the path in the database. 
7. The path to the image gets saved as default//favicon.png << (Notice the extra slash). 

We can see this again by querying the database. 
```
MariaDB [magento]> select * from core_config_data where path='design/head/shortcut_icon';
+-----------+---------+----------+---------------------------+--------------------------+
| config_id | scope   | scope_id | path                      | value                    |
+-----------+---------+----------+---------------------------+--------------------------+
|       368 | default |        0 | design/head/shortcut_icon | default//favicon-s_2.png |
+-----------+---------+----------+---------------------------+--------------------------+
1 row in set (0.00 sec)

MariaDB [magento]>
```
This causes the URL to the image to also include an extra slash after "default", which breaks links when using CloudFront and other CDN providers. 

The same behavior can be seen when uploading a Logo Image. 

**Steps to reproduce uploading a logo image:**
1. Enable extension as per wiki instructions and configure uploads to be uploaded to S3. 
2. Login to the Magento Admin Dashboard
3. Navigate to System >> Configuration >> Design
4. Click on the "Transactional Emails" section to expand it. 
5. Under the "Logo Image" option, click browse and upload a image (any image will work for testing purposes)
6. Click "Save Config" at the top to upload the image and save the path in the database. 
7. The path to the image gets saved as default//image.png << (Notice the extra slash). 

We can see this again by querying the database. 
```
MariaDB [magento]> select * from core_config_data where path='design/email/logo';
+-----------+---------+----------+-------------------+--------------------------------------+
| config_id | scope   | scope_id | path              | value                                |
+-----------+---------+----------+-------------------+--------------------------------------+
|       286 | default |        0 | design/email/logo | default//image.png |
+-----------+---------+----------+-------------------+--------------------------------------+
1 row in set (0.01 sec)

MariaDB [magento]>
```

This issue does not seem to occur when uploading product images. 

**Environment Information**
Magento: 1.9.2.4
PHP: 5.6.19

**My workaround for the moment:**
After uploading a favicon or logo image, update the path in the database and remove the extra slash after "default"

**Comment by thaiphan** [comment]
Hey @sjafferali,

Thanks for being so detailed with your bug report! Do you suspect that the extra slash is being added by our extension? If so, we can have a look to see if we can address this problem from our end. 

However, if that's not case, I would recommend figuring out what is causing the extra slash in the first place and fixing that instead! I'm kind of hesitant to make changes to this extension to cater random bugs caused by third parties.

Regards,

Thai

**Comment by sjafferali** [comment]
Yes, I believe it is being caused by this extension. When I change the storage configuration in System >> Configuration >> System >> Storage Configuration for Media, back to "File System", I am able to upload favicons and logo images without it placing the extra slash in the path. 

```
MariaDB [magento]> select * from core_config_data where path='design/head/shortcut_icon';
+-----------+---------+----------+---------------------------+---------------------------+
| config_id | scope   | scope_id | path                      | value                     |
+-----------+---------+----------+---------------------------+---------------------------+
|       369 | default |        0 | design/head/shortcut_icon | default/favicon-s_1_4.png |
+-----------+---------+----------+---------------------------+---------------------------+
1 row in set (0.00 sec)

MariaDB [magento]>
```

I have tested this on a new installation of Magento 1.9.2.4 with nothing other than the this extension installed as I originally suspected something else more likely to be causing it, but this does not appear to be the case as I was able to reproduce it on the new installation as well.

**Comment by thaiphan** [comment]
Hey @sjafferali,

Cool, I'll have a look then!

Regards,

Thai

**Comment by thaiphan** [comment]
Hey @sjafferali,

I've pushed a hotfix (v1.1.2) to address the problem you were experiencing. Here were the comments that I added to the commit.

> Images that were uploaded using the system configuration image upload widget,
> e.g. favicon, placeholder image, were getting an extra forward slash appended to
> them. This would cause a 404 error upon trying to download from S3.
> 
> This change will remove the forward slash from uploaded images. It also removed
> it from category and product images but I've tested them and they still work
> without the slash.

Can you confirm that everything is working as expected now?

Regards,

Thai

**Comment by thaiphan** [comment]
Hey @sjafferali,

Are you still having problems after installing the latest version?

Regards,

Thai

**Comment by sjafferali** [comment]
Hello @thaiphan,

Sorry, I did not get your previous notification for some reason. I'll test the update and post back shortly. 

Thanks for your help!

**Comment by sjafferali** [comment]
It seems to be working correctly now. Bug swashed. Thank you!
