### ISSUE TITLE
.thumbs directory inside wysiwyg folder

### ISSUE THREAD

**Issue by missoxd** [arkadedigital/magento-s3#5]
The .thumbs directory is not being created inside wysiwyg folder (it is created locally, but not on s3) ... there is something that i am missing?

Thank you

**Comment by thaiphan** [comment]
Hey @missoxd,

I'm pretty sure that the .thumbs folder is uploaded. I'll have a look and see what's up anyhow.

Regards,

Thai

**Comment by thaiphan** [comment]
Hey @missoxd,

I had a look and, yeah, it turns out that it was a bug! I have released v1.1.3 which will now upload the WYSIWYG thumbnails to S3.

Can you confirm that the bug has been fixed on your end?

Regards,

Thai

**Comment by missoxd** [comment]
Yep!
Thank you :D
