### ISSUE TITLE
Set up correctly but images are not loading on category pages

### ISSUE THREAD

**Issue by jeffminor** [arkadedigital/magento-s3#6]
I installed the extension, pushed everything to S3 through a separate python script that works faster, changed the config to store media in Amazon S3 and verified in core_config_data (i had to edit a template file to make synchronize not required so I could save), and then refreshed the page, but it is still referencing the images from the media directory on the server. I know because I removed a home page image from the server and now 404s instead of loading the one from S3. What am I doing wrong.

**Comment by thaiphan** [comment]
Hey @jeffminor,

Are you passing everything through to index.php? You need to pass the media location path through get.php.

Regards,

Thai

**Comment by thaiphan** [comment]
Hey @jeffminor,

Where are you at with this issue?

Regards,

Thai
