### ISSUE TITLE
Captcha Images are not pushing to S3

### ISSUE THREAD

**Issue by hemantshekhawat** [arkadedigital/magento-s3#7]
Hi,

After I installed the extension, all the media/* assets were pushed to S3. But in case of dynamic image generation, like captcha, the images are not pushed to S3.

How can I make a change for that?

**Comment by thaiphan** [comment]
Hey @hemantshekhawat,

Sorry for the late response. I'll try and get around to looking at this as soon as I can.

Regards,

Thai

**Comment by hemantshekhawat** [comment]
Thanks @thaiphan   ! Sooner, the better !

**Comment by thaiphan** [comment]
Hey @hemantshekhawat,

I've released an update 1.1.4 that uploads CAPTCHA images to S3. Can you update the extension and see if it works now?

Regards,

Thai

**Comment by hemantshekhawat** [comment]
Hi Thaiphan,

That update worked great. Thanks a lot.

I have another issue and logging it as an issue.


regards,
Hemant

**Comment by thaiphan** [comment]
Cool, I'll consider this issue solved then!
