### ISSUE TITLE
Extension not syncing compiled JS and CSS to S3

### ISSUE THREAD

**Issue by hemantshekhawat** [arkadedigital/magento-s3#8]
Hi Thaiphan,

The S3 has the one time push when we did init process. After that, whenever i clear my magento cache, the new files are created in the folders /media/js/* and media/css_secure/* but the same files are not getting pushed to S3 repo.

if this is available, please guide me how can it be done. Else, if you could add the functionality, that'd be great.

Thanks

**Comment by thaiphan** [comment]
Hey @hemantshekhawat,

Yeah I'll have a look.

Regards,

Thai

**Comment by gsomoza** [comment]
Any updates on this one? Is this a widespread issue?

**Comment by thaiphan** [comment]
Hey @hemantshekhawat and @gsomoza,

This extension doesn't currently handle the situation where people have configured Magento to use compiled JS and CSS. We will need update the extension so we also upload them to S3.

Regards,

Thai

**Comment by gsomoza** [comment]
Is that in the roadmap for anytime soon?

**Comment by thaiphan** [comment]
Hey @gsomoza,

I just tried to replicate the problem. I turned on compiled JS and CSS and then flushed the Javascript / CSS cache. However, everything seemed to be working fine!

Are you able to provide any more information on what your problem is?

Regards,

Thai

**Comment by gsomoza** [comment]
I'm not the one having this problem, I think @hemantshekhawat is. I was just going through the issues in this extension because we're considering to be used for a project.

**Comment by thaiphan** [comment]
Hey @gsomoza,

Cool. Please don't hesitate to create a new issue if you have anything you need us to action for you to jump onboard!

Regards,

Thai

**Comment by gsomoza** [comment]
Will do!

**Comment by thaiphan** [comment]
I'm closing this ticket because I was unable to replicate and OP has not responded in months. Please create a new issue if problems persist.
